### ISSUE TITLE
Add SMBIOS 20,1 and 20,2

### ISSUE THREAD

**Issue by Matgen84** [laobamac/OCLP-Mod#1]
Great work, thank you.

I use SMBIOS iMac20,1 for my Z390 system (Intel Wifi/BT 9560ac) on Sequoia 15.1 Beta 6. But I can't patch using OCLP-MOD despite csr config 0x803 (Clover). The patch button is grey out.

I don't know the reason. Maybe unlisted SMBIOS !

**Comment by laobamac** [comment]
Hello！Could you give me a photo of `Root-Patch`？Or you can use csr-active-config FF0F0000 and try it again.

**Comment by Matgen84** [comment]
Hello.  Another details: OCLP-Mod don't use my system language (French) or English. Only chinese is showing up. I upload screenshots.
Sorry for my bad English.
![Capture d’écran 2024-10-14 à 11 15 11](https://github.com/user-attachments/assets/b369f9ce-3130-44c1-a17a-1c1ab9d8d454)
![Capture d’écran 2024-10-14 à 11 15 44](https://github.com/user-attachments/assets/9cb3fed3-a8be-4b1f-a901-d2a17f309a1d)

**Comment by laobamac** [comment]
我是中国人🥳
你添加AMFIPass.kext了吗？你截图这个原因是没关AMFI。

**Comment by Matgen84** [comment]
I will try this kext. Thanks a lot.
