### ISSUE TITLE
After installing the software, it cannot be started,

### ISSUE THREAD

**Issue by kingtosh** [laobamac/OCLP-Mod#3]
When I install a new version of OLCP-MOD, it stops booting when the Apple logo appears.
If I press the option key to boot, I can even select the boot disk, but after selecting it, it stops and stays on a black screen.

The OS is sonoma 14.7.1.
The model is iMac 2019 21.5 inch model.

Best regards.

**Comment by laobamac** [comment]
Helllo！
I only tested this program on my Hackintosh and friend's MacBookPro14,2,maybe still has a few problems :(
Did you capture any photos or videos when you meet this problem?Please show them to me~

**Comment by kingtosh** [comment]
There are no photos or videos.
Also, I don't think I can make out any photos or videos because it either stops when I hear the boot sound and see the Apple logo, or the screen goes black after selecting the startup disk and stops there.
